version: 2
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6.6
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.create
      - run:
          name: Test
          command: mix test
      - store_test_results:
          path: _build/test/lib/phx_docker_service
  build_aws_cli:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
  deploy:
    docker:
      - image: circleci/elixir:1.6.6
    environment:
      MIX_ENV: prod
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: chmod +x ./ci ./ci/steps/*.sh
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: env MIX_ENV=prod mix do release.init, release --env=dev --verbose
      - run:
          name: Run Deployment
          command: ./ci/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # - test
      - deploy:
          requires:
            - build_aws_cli
          #   - test
          # filters:
          #   branches:
          #     only: master
