version: 2
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6.6
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.create
      - run:
          name: Test
          command: mix test
      - store_test_results:
          path: _build/test/lib/phx_docker_service
  deploy:
    docker:
      - image: circleci/elixir:1.6.6
        environment:
          MIX_ENV: prod
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:
      - image: neo4j:3.4.5
    steps:
      - checkout
      - setup_remote_docker
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run:
          name: Get Dependencies & compile
          command: mix do deps.get, compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: createuser --interactive -P
      - run: mix ecto.create
      # - run:
      #     name: Semantic Release
      #     command:  semantic-release -vf -slug leifg/time_tracking -noci || true
      - run:
          name: Run Deployment
          command: chmod +x ./ci ./ci/steps/*.sh && ./ci/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # - test
      - deploy
      # - deploy:
          # requires:
          #   - test
          # filters:
          #   branches:
          #     only: master
