version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:latest
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.create
  test:
    docker:
      - image: circleci/elixir:latest
        environment:
          MIX_ENV: test
    working_directory: ~/app
    steps:
      # - attach_workspace:
      #     at: /
      - run: pwd
      - run: ls -la
      - run:
          name: Test
          command: mix test
      - store_test_results:
          path: _build/test/lib/phx_docker_service
  deploy:
    docker:
      - image: circleci/elixir:latest
        environment:
          MIX_ENV: prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Get Dependencies
          command: mix deps.get
      # - run:
      #     name: Semantic Release
      #     command:  semantic-release -vf -slug leifg/time_tracking -noci || true
      - run:
          name: Run Deployment
          command: ci/deploy.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
