version: 2
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6.6
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.create
      - run:
          name: Test
          command: mix test
      - store_test_results:
          path: _build/test/lib/phx_docker_service

  deploy:
    docker:
      - image: circleci/elixir:1.6.6
    environment:
      MIX_ENV: prod
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install awscli
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get -y install awscli
      # - run: chmod +x ./ci ./ci/steps/*.sh
      # - run: mix local.hex --force
      # - run: mix local.rebar --force
      # - run: mix deps.get
      # - run: MIX_ENV=prod mix do release.init, release
      # - run: export PACKAGE="./_build/prod/rel/${SERVICE_NAME}/releases/`cat VERSION`/${SERVICE_NAME}.tar.gz"
      - run: ssh -o StrictHostKeyChecking=no -l $AWS_USER $AWS_HOST
      - run: scp -i ~/.ssh/id_rsa ./VERSION "${AWS_USER}@${AWS_HOST}:~/${SERVICE_NAME}"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      # - test
      - deploy
          # filters:
          #   branches:
          #     only: master
